# azure-pipelines-docker-build-push-jfrog.yml
parameters:
  dockerfilePath: 'Dockerfile'
  imageName: 'my-docker-image'
  imageTag: '$(Build.BuildId)' # Use build ID as default tag
  jfrogConnection: 'scm-reporting' # Name of your JFrog Artifactory service connection
  jfrogRegistry: 'my-docker-registry.jfrog.io' # Your JFrog Artifactory Docker registry URL
  jfrogRepo: 'my-docker-repo' # The target repository in Artifactory
  buildContext: '.' # Context for the Docker build
  additionalBuildArgs: '' # Additional docker build arguments
  additionalPushArgs: '' # Additional docker push arguments

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image to JFrog'
  steps:        
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      repository: '${{ parameters.jfrogRegistry }}/${{ parameters.jfrogRepo }}/${{ parameters.imageName }}'
      command: 'build'
      Dockerfile: ${{ parameters.dockerfilePath }}
      tags: ${{ parameters.imageTag }}
  - task: ArtifactoryDocker@1
    displayName: 'Push Image to Jfrog'
    inputs:
      command: 'push'
      artifactoryService: ${{ parameters.jfrogConnection }}
      targetRepo: ${{ parameters.jfrogRepo }}
      imageName: '${{ parameters.jfrogRegistry }}/${{ parameters.jfrogRepo }}/${{ parameters.imageName }}:${{ parameters.imageTag }}'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      includeEnvVars: true