parameters:

  - name: vmImageName
    default: 'ubuntu-latest'
  - name: projectRoot
    default: '$(System.DefaultWorkingDirectory)'
  - name: pythonVersion
    default: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.pythonVersion }}
      displayName: 'Use Python version ${{ parameters.pythonVersion }}'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
      workingDirectory: ${{ parameters.projectRoot }}
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '${{ parameters.projectRoot }}'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Artifact_Name).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Artifact_Name).zip
      displayName: 'Upload package'
      artifact: $(Artifact_Name)
